//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campaigns {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CampaignsStringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CampaignsStringResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campaigns.CampaignsStringResource", typeof(CampaignsStringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die base.png ähnelt.
        /// </summary>
        internal static string IconBase {
            get {
                return ResourceManager.GetString("IconBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die idle.png ähnelt.
        /// </summary>
        internal static string IconIdle {
            get {
                return ResourceManager.GetString("IconIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        internal static string SaveHeader {
            get {
                return ResourceManager.GetString("SaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite Save? ähnelt.
        /// </summary>
        internal static string SaveQuestion {
            get {
                return ResourceManager.GetString("SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays the Character Informations of your Party. ähnelt.
        /// </summary>
        internal static string ToolTipChar {
            get {
                return ResourceManager.GetString("ToolTipChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Putting up a fight eh? ähnelt.
        /// </summary>
        internal static string ToolTipFight {
            get {
                return ResourceManager.GetString("ToolTipFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can Interact with something, might blow up though. ähnelt.
        /// </summary>
        internal static string ToolTipInteract {
            get {
                return ResourceManager.GetString("ToolTipInteract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays the Inventory of your Party. ähnelt.
        /// </summary>
        internal static string ToolTipInventory {
            get {
                return ResourceManager.GetString("ToolTipInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays your Log. ähnelt.
        /// </summary>
        internal static string ToolTipLog {
            get {
                return ResourceManager.GetString("ToolTipLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Look but don&apos;t touch, just as your old Ma told you. ähnelt.
        /// </summary>
        internal static string ToolTipLook {
            get {
                return ResourceManager.GetString("ToolTipLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Moves your Party. ähnelt.
        /// </summary>
        internal static string ToolTipMove {
            get {
                return ResourceManager.GetString("ToolTipMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can Talk with the Person or Object for that matter. ähnelt.
        /// </summary>
        internal static string ToolTipTalk {
            get {
                return ResourceManager.GetString("ToolTipTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can step on it, to Heaven or to Hell the Bell invites us. ähnelt.
        /// </summary>
        internal static string ToolTipTeleport {
            get {
                return ResourceManager.GetString("ToolTipTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can Trade Goods, provided you have enough cash. ähnelt.
        /// </summary>
        internal static string ToolTipTrade {
            get {
                return ResourceManager.GetString("ToolTipTrade", resourceCulture);
            }
        }
    }
}
